### ISSUE TITLE
smh p盘何时有收益

### ISSUE THREAD

**Issue by wwltq** [spacemeshos/wiki#1]
3.3之前p 的盘，3.4不参与poet吗？何时参与

**Comment by fasmat** [comment]
English:

If you finished initialization before March 3rd and were online during the cyclegap March 3rd to March 4th you need to be online until March 18th for your node to be able to publish an ATX. This will make you eligible to get rewards in Epoch 18, which starts on March 22th and ends on April 5th.
Our reward system requires you to hold the PoST data on disk for at least 2 weeks to be eligible for rewards. Depending on when your node first came online you might need to wait up to 4 weeks to get your first rewards.

Chinese (computer translated):

如果您在 3 月 3 日之前完成初始化，并且在 3 月 3 日至 3 月 4 日的周期间隙期间在线，则需要在 3 月 18 日之前在线，您的节点才能发布 ATX。 这将使您有资格在 3 月 22 日开始至 4 月 5 日结束的第 18 纪元中获得奖励。
我们的奖励系统要求您将 PoST 数据保存在磁盘上至少 2 周才有资格获得奖励。 根据您的节点首次上线的时间，您可能需要等待长达 4 周才能获得第一份奖励。
